package ru.Dolgorukov.city;

import java.util.ArrayList;

public class TestCity {
    public void testCity() {
        Way way1 = new Way();
        Way way2 = new Way();
        Way way3 = new Way();
        Way way4 = new Way();
        Way way5 = new Way();
        Way way6 = new Way();
        Way way7 = new Way();
        Way way8 = new Way();
        Way way9 = new Way();
        Way way10 = new Way();
        Way way11 = new Way();
        Way way12 = new Way();
        Way way13 = new Way();
        ArrayList<Way> ways1 = new ArrayList<>();
        way1.setTitlePrice("B", 5);
        way2.setTitlePrice("F", 1);
        way3.setTitlePrice("D", 6);
        ways1.add(way1);
        ways1.add(way2);
        ways1.add(way3);
        Cities city1 = new Cities("A", ways1);
        ways1.clear();
        way4.setTitlePrice("A", 5);
        way5.setTitlePrice("C", 3);
        ways1.add(way4);
        ways1.add(way5);
        Cities city2 = new Cities("B", ways1);
        ways1.clear();
        way6.setTitlePrice("B", 3);
        way7.setTitlePrice("D", 4);
        ways1.add(way6);
        ways1.add(way7);
        Cities city3 = new Cities("C", ways1);
        ways1.clear();
        way8.setTitlePrice("C", 4);
        way9.setTitlePrice("E", 2);
        way10.setTitlePrice("A", 6);
        ways1.add(way8);
        ways1.add(way9);
        ways1.add(way10);
        Cities city4 = new Cities("D", ways1);
        ways1.clear();
        way11.setTitlePrice("F", 2);
        ways1.add(way11);
        Cities city5 = new Cities("E", ways1);
        ways1.clear();
        way12.setTitlePrice("B", 1);
        way13.setTitlePrice("E", 2);
        ways1.add(way12);
        ways1.add(way13);
        Cities city6 = new Cities("F", ways1);
        ways1.clear();
        System.out.println("Исходные города:");
        System.out.println(city1.toString());
        System.out.println(city2.toString());
        System.out.println(city3.toString());
        System.out.println(city4.toString());
        System.out.println(city5.toString());
        System.out.println(city6.toString());
        System.out.println("Попытка добавить дублирующую дорогу в город A:");
        city1.addWay("B", 10);
        System.out.println("Добавляем новую дорогу из A в C:");
        city1.addWay("C", 7);
        System.out.println(city1.toString());
        System.out.println("Удаляем дорогу из A в F (индекс 1):");
        city1.deleteWay(1);
        System.out.println(city1.toString());
        System.out.println("Поиск маршрута из F в D");
        Cities[] allCities = {city1, city2, city3, city4, city5, city6};
        Route route = new Route(city6, city4, allCities);
        System.out.println("Маршрут: " + route.toString());
        System.out.println("Сравнение городов");
        ArrayList<Way> testWays1 = new ArrayList<>();
        testWays1.add(new Way("X", 1));
        testWays1.add(new Way("Y", 2));
        ArrayList<Way> testWays2 = new ArrayList<>();
        testWays2.add(new Way("X", 1));
        testWays2.add(new Way("Y", 2));
        Cities testCity1 = new Cities("City1", testWays1);
        Cities testCity2 = new Cities("City2", testWays2);
        System.out.println("Город 1: " + testCity1.getCityName() + " с дорогами: " + testWays1);
        System.out.println("Город 2: " + testCity2.getCityName() + " с дорогами: " + testWays2);
        System.out.println("Города равны по наборам дорог? " + testCity1.equals(testCity2));
        System.out.println("Города A и B равны? " + city1.equals(city2));
    }
}
